### ISSUE TITLE
Outdated readme?

### ISSUE THREAD

**Issue by larsfagerbakke** [MCUdude/microUPDI#21]
I tried to follow the instructions (https://github.com/MCUdude/microUPDI), but I'm having some issues.

> Usage
> After the Pro Micro is flashed with mEDBG firmware it will present itself to the computer as an mEDBG CMSIS-DAP device. In Atmel Studio it will show up as a generic mEDBG device, while in Arduino IDE it will show up as an *Arduino UNO WiFi Rev2.
> 
> If you're using the microUPDI programmer with [megaTinyCore](https://github.com/SpenceKonde/megaTinyCore) you just select the Onboard Atmel mEDBG option in the Programmers menu. For [MegaCoreX](https://github.com/MCUdude/MegaCoreX) it's Atmel mEDBG (microUPDI).

Getting board info ARduino IDE states unknown board. Looking at the device registry in Windows "bus reported device description" states "mEDBG CDC", so I think I managed to make programmer out of my nano (?).

I've downloaded megaTinyCore but there is on Onboard Atmel mEDBG option. Are you able to update your documentation?

**Comment by MCUdude** [comment]
Hi, and sorry for the late reply. I've been on "påskeferie", but I'm back home now.

> Getting board info ARduino IDE states unknown board. 

> I've downloaded megaTinyCore but there is on Onboard Atmel mEDBG option. Are you able to update your documentation?

I'll assume you meant _no_ Onboard Atmel mEDBG option? The correct programmer option should be `Xplained Mini (mEDBG, debug chip: ATmega32u4)` when using megaTinyCore.
