### ISSUE TITLE
I'm stuck. Unable to flash the Arduino Pro Micro as microUPDI programmer

### ISSUE THREAD

**Issue by jaccobezemer** [MCUdude/microUPDI#22]
Hello,

I have a working Pro Micro. Uploaded the Pro Micro Test Code and I get blinking LEDs.

When I select microUPDI Firmware Uploader from the boards menu and click the upload button I get an error.

```
FQBN: microUPDIcore:avr:microupdi
Using board 'microupdi' from platform in folder: C:\Users\jacco\AppData\Local\Arduino15\packages\microUPDIcore\hardware\avr\1.0.2
Using core 'arduino' from platform in folder: C:\Users\jacco\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.8.6

Detecting libraries used...
C:\Users\jacco\AppData\Local\Arduino15\packages\microUPDIcore\hardware\avr\1.0.2/scripts/dummy-preproc-macros-command.bat C:\Users\jacco\AppData\Local\Temp\arduino\sketches\AE9949AC16C921D4D53471318DBE9348/preproc ctags_target_for_gcc_minus_e.cpp
Error while detecting libraries included by C:\Users\jacco\AppData\Local\Temp\arduino\sketches\AE9949AC16C921D4D53471318DBE9348\sketch\sketch_apr19a.ino.cpp
Generating function prototypes...
C:\Users\jacco\AppData\Local\Arduino15\packages\microUPDIcore\hardware\avr\1.0.2/scripts/dummy-preproc-macros-command.bat C:\Users\jacco\AppData\Local\Temp\arduino\sketches\AE9949AC16C921D4D53471318DBE9348/preproc ctags_target_for_gcc_minus_e.cpp
The system cannot find the path specified.
exit status 1

Compilation error: exit status 1
```

What path can't be found? What am I missing?

**Comment by jaccobezemer** [comment]
So I still don't know why I get the error.
But I managed to upload the firmware using a modified version of scripts\CLI flash script\Load_firmware.bat and a Arduino UNO as Arduino ISP.
It looks like a got a working microUPDI programmer as I managed to upload firmware to an ATMega4809.

**Comment by MCUdude** [comment]
Hi!
Sorry for the late reply! Great to hear you managed to upload the firmware through the alternative script provided. I'll try to look into why you weren't able to upload the firmware using the IDE.
