### ISSUE TITLE
working with Platformio

### ISSUE THREAD

**Issue by paulskirk53** [MCUdude/microUPDI#7]
Hi, I have the microUPDI, can I get it to debug code on an AVR 4809 using Platformio? Any help to configure would be much appreciated.

**Comment by maxgerhardt** [comment]
Per topic in https://community.platformio.org/t/debug-an-avr-4809-with-microupdi/19926/18?u=maxgerhardt it worked by adding 

```ini
upload_protocol = custom
upload_flags =
    -C
    $PROJECT_PACKAGES_DIR/tool-avrdude-megaavr/avrdude.conf
    -p
    $BOARD_MCU
    -c
    xplainedmini_updi
    -Pusb
    -b115200
upload_command = avrdude $UPLOAD_FLAGS -U flash:w:$SOURCE:i
``´

to the `platformio.ini`, after seeing the info in https://github.com/MCUdude/microUPDI#usage.

**Comment by MCUdude** [comment]
> Hi, I have the microUPDI, can I get it to debug code on an AVR 4809 using Platformio? Any help to configure would be much appreciated.

PlatformIO doesn't support AVR debugging natively. You'll have to use Atmel Studio, MPLAB X, set up your own GDB to do this or follow the guide that @maxgerhardt linked to.
